# Generated by Django 6.0.6 on 2026-07-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('writeoff', 'Списание'), ('transfer', 'Перемещение'), ('adjust', 'Корректировка')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='+ приход / − расход', max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('reference', models.CharField(blank=True, help_text='Документ-основание', max_length=255)),
            ],
            options={
                'verbose_name': 'Движение товара',
                'verbose_name_plural': 'Движения товара',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.variant')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
    ]
