# Generated by Django 6.0.6 on 2026-07-12 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.variant'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenants.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', '-created_at'], name='inventory_s_tenant__a08bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse', 'variant'], name='inventory_s_warehou_f890e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'variant'), name='uniq_stock_wh_variant'),
        ),
    ]
